FROM node:18-alpine
RUN mkdir /app
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN yarn
RUN yarn global add pm2
CMD [ "pm2-runtime", "npm", "run", "--", "start"]